"""add users table

Revision ID: 834003c339bd
Revises: 8da48471d1e8
Create Date: 2024-10-12 00:26:20.867432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.encrypted.encrypted_type import StringEncryptedType


# revision identifiers, used by Alembic.
revision: str = '834003c339bd'
down_revision: Union[str, None] = '8da48471d1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belonging_chat_id', sa.Integer(), nullable=False),
    sa.Column('first_name', StringEncryptedType(), nullable=True),
    sa.Column('last_name', StringEncryptedType(), nullable=True),
    sa.Column('username', StringEncryptedType(), nullable=True),
    sa.ForeignKeyConstraint(['belonging_chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
