"""add users table

Revision ID: 9a8f122e0116
Revises: 58c0ce098645
Create Date: 2024-10-09 17:19:10.109177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.encrypted.encrypted_type import StringEncryptedType

# revision identifiers, used by Alembic.
revision: str = '9a8f122e0116'
down_revision: Union[str, None] = '58c0ce098645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belonging_chat_id', sa.Integer(), nullable=False),
    sa.Column('user_info', StringEncryptedType(), nullable=True),
    sa.Column('added_date', StringEncryptedType(), nullable=True),
    sa.ForeignKeyConstraint(['belonging_chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
