"""add user table

Revision ID: c38478ccbc7b
Revises: 
Create Date: 2024-10-09 01:12:54.884153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel as sm
from sqlalchemy_utils import StringEncryptedType


# revision identifiers, used by Alembic.
revision: str = 'c38478ccbc7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', StringEncryptedType(), nullable=True),
    sa.Column('telegram_id', StringEncryptedType(), nullable=True),
    sa.Column('additor_name', sm.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('leaved', sa.Boolean(), nullable=False),
    sa.Column('leaved_date', sa.DateTime(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
